# WHAT: Contextual query rewriter resolving conversational pronouns and follow-up ambiguity in multi-turn dialogues.
# WHY: Implements Layer 3 Linguistic Pre-Processing according to Section III-B of the architecture spec.
#      In realistic multi-turn student conversations, follow-up queries frequently contain unresolved pronouns
#      or missing subjects (e.g., "When is its last date?" or "Where do I submit this?").
#      Passing such ambiguous queries directly to the retrieval engine causes severe context failure because
#      neither dense (BGE-M3) nor sparse (BM25) search can identify the referenced topic.
#      This module leverages Mistral 7B to rewrite the follow-up query into a complete standalone question.

from typing import List, Dict, Any
import ollama
from config import OLLAMA_MODEL

# WHAT: System instructions for Mistral 7B guiding contextual query rewriting.
# WHY: Instructs the model to output strictly the rewritten standalone query without conversational chatter,
#      explanations, or question-answering behavior. Includes clear 1-shot demonstration.
REWRITE_SYSTEM_PROMPT = """You are a query rewriting assistant for an academic institution chatbot.
Given a conversation history and a follow-up query, rewrite the follow-up query into a complete, standalone question that incorporates the necessary context from previous turns (such as the specific subject, form, notice, or event being discussed).
Resolve all conversational pronouns (such as it, its, they, their, this, that, these, those).
Do NOT answer the question. Do NOT add conversational filler or explanations.
Output ONLY the single rewritten standalone question.

Example:
Conversation history:
User: Tell me about the scholarship form
Bot: The scholarship form is available on the college portal.
Follow-up query: When is its last date?
Standalone query: When is the last date for the scholarship form?"""


# WHAT: Rewrites a conversational follow-up query into a self-contained standalone search query.
# WHY: Multi-turn conversational context resolution:
#      1. If conversation history is empty, the query is already initial/standalone -> returns immediately.
#      2. Formats the last 2-4 conversational turns as dialogue context.
#      3. Calls Mistral 7B via Ollama with zero temperature for deterministic rewrites.
#      4. Strips formatting artifacts, surrounding quotes, or accidental prefix labels.
#      5. Employs defensive error handling: if Ollama is unreachable, falls back safely to the original query.
def rewrite_query(query: str, history: List[Dict[str, str]] = None) -> str:
    """
    Resolves pronouns and follow-up references using conversational history.
    Example: 'When is its last date?' -> 'When is the last date for the scholarship form?'
    If history is empty or query is already standalone, returns query unchanged.
    """
    if not query or not query.strip():
        return ""

    # If no conversational history exists, query is already standalone
    if not history:
        return query.strip()

    # Filter and format the last 4 turns (up to 2 complete user/assistant cycles)
    relevant_history = history[-4:]
    history_lines = []
    for msg in relevant_history:
        role_label = "User" if msg.get("role") in ("user", "student") else "Bot"
        content = msg.get("content", "").strip()
        if content:
            history_lines.append(f"{role_label}: {content}")

    if not history_lines:
        return query.strip()

    history_text = "\n".join(history_lines)

    user_prompt = f"""Conversation history:
{history_text}

Follow-up query: {query.strip()}
Standalone query:"""

    try:
        response = ollama.chat(
            model=OLLAMA_MODEL,
            messages=[
                {"role": "system", "content": REWRITE_SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt}
            ],
            options={"temperature": 0.0, "num_predict": 50}
        )
        rewritten = response.get("message", {}).get("content", "").strip()

        # Clean up any potential prefixes or quotes generated by the model
        for prefix in ("Standalone query:", "Rewritten query:", "Query:"):
            if rewritten.lower().startswith(prefix.lower()):
                rewritten = rewritten[len(prefix):].strip()

        # Strip surrounding double or single quotes
        rewritten = rewritten.strip("\"' \n")

        # If rewrite returned an empty string, fallback to original query
        return rewritten if rewritten else query.strip()

    except Exception as e:
        # Fallback to original query on any connection/model error to ensure pipeline continuity
        print(f"[QUERY_REWRITER] Warning: Ollama rewrite failed ({e}), using original query.")
        return query.strip()
